# Funding options for TUI Dashboard Designer

github: aerocyberlabs
# ko_fi: # Uncomment and add your Ko-fi username if you create one
# buy_me_a_coffee: # Uncomment and add your Buy Me a Coffee username if you create one
# patreon: # Uncomment and add your Patreon username if you create one